---
arenas:
- id: "1"
  capacity: "1"
  spawnpoints:
  - x: 77.763855
    "y": 76.000003
    z: 195.330750
    level: world
  - x: 77.763855
    "y": 76.000003
    z: 195.330750
    level: world
chests:
- id: 54
  x: 79
  "y": 71
  z: 212
  level: 1
- id: 54
  x: 83
  "y": 71
  z: 213
  level: 1
lobby:
  x: 81.306961
  "y": 72.000003
  z: 209.568298
  level: world
chestitems:
  - 267
  - 298
  - 299
  - 300
  - 302
  - 303
  - 304
  - 306
  - 307
  - 308
...
